name: Prisma Cloud Shift Left demo
on: [ pull_request ]

jobs:
  prisma_cloud_job:
    runs-on: ubuntu-latest
    name: Run Prisma Cloud steps 
    env:
          TL_USER: ${{ secrets.TL_USER }}
          TL_PASS: ${{ secrets.TL_PASS }}
          TL_CONSOLE: "console-master-pasq.prussiello.demo.twistlock.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      
      
        
      - name: Runtime attacks
        run: bash files/exec.sh runtime_attacks.sh
        
     # - name: WAAS attacks
     #   run: bash files/exec.sh waas_attacks.sh
