name: Prisma Cloud IaC Scan Example
on: [ pull_request ]

jobs:
  prisma_cloud_iac_scan:
    runs-on: ubuntu-latest
    name: Run Prisma Cloud IaC Scan to check 
    env:
          TL_USER: ${{ secrets.TL_USER }}
          TL_PASS: ${{ secrets.TL_PASS }}
          TL_CONSOLE: "console-master-pasq.prussiello.demo.twistlock.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check image Git dependencies has no vulnerabilities
        run: bash ./files/checkGit.sh
   

      
      
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: kubernetes # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          quiet: true
          output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only
          log_level: DEBUG # optional: set log level. Default WARNING
